apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - image: game-of-set-server
        name: server
        imagePullPolicy: Never
        ports:
        - containerPort: 8228
          name: server
        env:
        - name: SERVER_PORT
          value: "8228"
        - name: MONGO_URL
          value: mongodb://db
        - name: REDIS_URL
          value: redis://redis:6379
        - name: DISABLE_SECURITY
          value: "alpha"
